### ISSUE TITLE
De question

### ISSUE THREAD

**Issue by Kirll-cpu** [NoobLikesThis/Project-Urly#1]
Where did you got those? I'm so into beta/dev/alpha/canary stuff!

**Comment by NoobLikesThis** [comment]
go to a github, then go to actions

**Comment by NoobLikesThis** [comment]
idk how to make exes

**Comment by Kirll-cpu** [comment]
oh ok, so, something else, or..?

**Comment by Kirll-cpu** [comment]
oh! nvm i see now, thank you so much!
